### ISSUE TITLE
Wrong window size plugin SEILAPLAN

### ISSUE THREAD

**Issue by zsoma88** [piMoll/SEILAPLAN#4] opened 2024-09-12 09:05 UTC
<img width="1440" alt="Screenshot 2024-09-12 alle 09 48 03" src="https://github.com/user-attachments/assets/b962dca5-436f-4bc0-86a5-57718c412d77">

I have worked previously with the SEILAPLAN plugin and have never encountered any difficulties on macOS. Since upgrading to the latest version (3.6.1) I have encountered the following problem. I am using the LTR version of QGIS (3.34.10-Prizren). 

I have been using the plugin today but the working window of the plugin itself turns out to be too large in size, making it impossible to run the manual or automatic simulation for tracing the zip line. It is not possible to resize the window as is normally done with QGIS interfaces.

**Comment by piMoll** [comment] 2024-09-13 09:43
Thanks for reporting this.
I think I know what the problem is: I fixed another problem with macOS plugin window behaviour in release 3.6.0 and possibly introduced this new issue. It's a bit tricky to fix macOS problems since I don't have access to a mac. 

This should be fixed by Monday morning, though. Have a look for a Seilaplan update on Monday.

**Closed as completed** 2024-09-16 08:21 UTC
Labels: bug
